url: https://www.skypointfarm.com
baseurl: ""

# Site settings
title: Skypoint Farm
email: hello@skypointfarm.com
description: "Skypoint Farm is a full service Hunter Jumper facility in Newbury, Ohio."

# Team names, titles and social links
people:
  - name: Redean Sheppard
    pic: 4
    position: Owner & Coach
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Stephanie Keough
    pic: 5
    position: Coach, IEA & IHSA
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Alex Shokat
    pic: 6
    position: Trainer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: linkedin
        url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/skypointfarm/

# Postal address (add as many lines as necessary)
address:
  - line: 10810 Music Street
  - line: Newbury, OH 44065

# Build settings
markdown: kramdown
permalink: pretty
