url: https://www.skypointfarm.com
baseurl: ""

# Site settings
title: Skypoint Farm
email: hello@skypointfarm.com
description: "Skypoint Farm is a full service Hunter Jumper facility in Newbury, Ohio."

# Team names, titles and social links
# Pics need to go in img/team and be sized to 225x225px!
people:
  - name: Redean Sheppard
    pic: 4
    position: Owner & Coach
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Stephanie Keough
    pic: 5
    position: Coach, IEA & IHSA
    # You can comment these out like so or delete the socials lines if you don't want them.
    # social:
    #   - title: twitter
    #     url: #
    #   - title: facebook
    #     url: #
    #   - title: linkedin
    #     url: #

  - name: New Lady Trainer
    pic: 3
    position: Trainer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: linkedin
        url: #

#
# Site Footer Information
#

# Social networks & contact methods
#
# Here, the "title" is really the name of the FontAwesome icon you want. (https://fontawesome.com/)
# e.g., "facebook" is a FontAwesome "fa-facebook" icon, and "phone" is the "fa-phone" icon.
# You can search through `/css/font-awesome/css/font-awesome.css` for the names of other icons.
# (Note that the FontAwesome website has new and different icons that this theme doesn't have.)
social:
  - title: facebook
    url: https://www.facebook.com/skypointfarm/
  - title: envelope-o
    url: mailto:hello@skypointfarm.com
  - title: phone
    url: tel:+1-724-777-3344
  - title: map-marker
    url: https://maps.app.goo.gl/ZvsC7kedPNoGEg2z7

# Postal address (add as many lines as necessary)
address:
  - line: 10810 Music Street,
  - line: Newbury, OH 44065

# Company phone number
phone: +1 (724) 777-3344

# Build settings
markdown: kramdown
permalink: pretty
